version: '3.8'

services:
  db:
    image: postgres:15
    container_name: go_api_db
    restart: always
    environment:
      POSTGRES_USER: komang
      POSTGRES_PASSWORD: komang
      POSTGRES_DB: goapi
    ports:
      - "5432:5432"
